# Generated by Django 5.0.6 on 2024-07-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('soup', 'Первые блюда'), ('second_course', 'Вторые блюда'), ('salad', 'Салаты'), ('grill', 'Мангал'), ('dessert', 'Десерты'), ('drink', 'Напитки')], default='', max_length=15)),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(blank=True, default='Recipe Image', null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=800)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('recipe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=1200)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
