# Generated by Django 5.0.6 on 2024-07-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(null=True),
        ),
    ]
