# Generated by Django 5.0.6 on 2024-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_description_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
