# Generated by Django 5.0.6 on 2024-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount_ingredient',
            field=models.CharField(default='', max_length=15),
        ),
    ]
