# Generated by Django 5.0.6 on 2024-06-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_serving_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
