# Generated by Django 5.0.6 on 2024-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_amount_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(max_length=230),
        ),
    ]
