# Generated by Django 5.0.6 on 2024-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='description',
            field=models.CharField(max_length=106),
        ),
    ]
