# Generated by Django 5.0.6 on 2024-06-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_serving_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Serving',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
