# Generated by Django 5.0.6 on 2024-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serving',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
