# Generated by Django 5.0.6 on 2024-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('soup', 'Первое блюдо'), ('second_course', 'Второе блюдо'), ('salad', 'Салат'), ('grill', 'Мангал'), ('dessert', 'Десерт'), ('drink', 'Напиток')], default='', max_length=15),
        ),
    ]
