# Generated by Django 5.0.6 on 2024-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('soup', 'Первые блюда'), ('second_course', 'Вторые блюда'), ('salad', 'Салаты'), ('grill', 'Мангал'), ('dessert', 'Десерты'), ('drink', 'Напитки')], default='', max_length=15),
        ),
    ]
