# Generated by Django 5.0.6 on 2024-07-09 10:36

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='images'),
        ),
    ]
