# Generated by Django 5.0.6 on 2024-07-09 14:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[190, 190], upload_to='images'),
        ),
    ]
